# Generated by Django 5.0 on 2024-09-02 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_rename_quanity_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
