# Generated by Django 5.0 on 2024-09-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_alter_shippingaddress_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(auto_now=True)),
                ('item_quantity', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.product')),
            ],
        ),
        migrations.AlterField(
            model_name='customercart',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shopping_cart.orderitem'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
