# Generated by Django 5.0 on 2024-09-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0006_alter_orderitem_product_alter_product_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='shopping_ca_slug_734746_idx'),
        ),
    ]
