# Generated by Django 5.0 on 2024-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_product_shopping_ca_slug_734746_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping addresses'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='date_ordered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
